spring:
  profiles:
    include: oauth,real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  session:
    store-type: jdbc